-- MySQL Script generated by MySQL Workbench
-- Wed Apr 12 10:39:55 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema next-games-grupo8
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema next-games-grupo8
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `next-games-grupo8` DEFAULT CHARACTER SET utf8 ;
USE `next-games-grupo8` ;

-- -----------------------------------------------------
-- Table `next-games-grupo8`.`rols`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `next-games-grupo8`.`rols` ;

CREATE TABLE IF NOT EXISTS `next-games-grupo8`.`rols` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `rol` VARCHAR(45) NULL DEFAULT 'user',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `next-games-grupo8`.`addresses`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `next-games-grupo8`.`addresses` ;

CREATE TABLE IF NOT EXISTS `next-games-grupo8`.`addresses` (
  `id` INT NOT NULL,
  `address` VARCHAR(255) NOT NULL,
  `city` VARCHAR(255) NOT NULL,
  `province` VARCHAR(45) NOT NULL,
  `zipCode` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `next-games-grupo8`.`usuarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `next-games-grupo8`.`usuarios` ;

CREATE TABLE IF NOT EXISTS `next-games-grupo8`.`usuarios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `user_name` VARCHAR(255) NOT NULL,
  `image` VARCHAR(255) NULL,
  `rol_id` INT NULL,
  `address_id` INT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `password_UNIQUE` (`password` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  UNIQUE INDEX `user_name_UNIQUE` (`user_name` ASC) VISIBLE,
  INDEX `fk_usuarios_rols_idx` (`rol_id` ASC) VISIBLE,
  INDEX `fk_usuarios_addresses_idx` (`address_id` ASC) VISIBLE,
  CONSTRAINT `fk_usuarios_rols`
    FOREIGN KEY (`rol_id`)
    REFERENCES `next-games-grupo8`.`rols` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuarios_addresses`
    FOREIGN KEY (`address_id`)
    REFERENCES `next-games-grupo8`.`addresses` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `next-games-grupo8`.`orders`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `next-games-grupo8`.`orders` ;

CREATE TABLE IF NOT EXISTS `next-games-grupo8`.`orders` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `date` DATETIME NULL,
  `total` INT NULL,
  `user_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_orders_usuarios_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_orders_usuarios`
    FOREIGN KEY (`user_id`)
    REFERENCES `next-games-grupo8`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `next-games-grupo8`.`Estado`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `next-games-grupo8`.`Estado` ;

CREATE TABLE IF NOT EXISTS `next-games-grupo8`.`Estado` (
  `id` INT NOT NULL,
  `images` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `next-games-grupo8`.`category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `next-games-grupo8`.`category` ;

CREATE TABLE IF NOT EXISTS `next-games-grupo8`.`category` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `estado_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `estado_id_idx` (`estado_id` ASC) VISIBLE,
  CONSTRAINT `estado_id`
    FOREIGN KEY (`estado_id`)
    REFERENCES `next-games-grupo8`.`Estado` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `next-games-grupo8`.`products`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `next-games-grupo8`.`products` ;

CREATE TABLE IF NOT EXISTS `next-games-grupo8`.`products` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `price` INT NOT NULL,
  `discount` INT NOT NULL,
  `description` VARCHAR(1000) NOT NULL,
  `visible` TINYINT(1) NULL,
  `category_id` INT NULL,
  `image` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_products_category_idx` (`category_id` ASC) VISIBLE,
  CONSTRAINT `fk_products_category`
    FOREIGN KEY (`category_id`)
    REFERENCES `next-games-grupo8`.`category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `next-games-grupo8`.`carts`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `next-games-grupo8`.`carts` ;

CREATE TABLE IF NOT EXISTS `next-games-grupo8`.`carts` (
  `id` INT NOT NULL,
  `quantity` INT NULL,
  `product_id` INT NULL,
  `order_id` INT NULL,
  `address_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_cart_orders_idx` (`order_id` ASC) VISIBLE,
  INDEX `fk_cart_addresses_idx` (`address_id` ASC) VISIBLE,
  INDEX `fk_cart_products_idx` (`product_id` ASC) VISIBLE,
  CONSTRAINT `fk_cart_orders`
    FOREIGN KEY (`order_id`)
    REFERENCES `next-games-grupo8`.`orders` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cart_addresses`
    FOREIGN KEY (`address_id`)
    REFERENCES `next-games-grupo8`.`addresses` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cart_products`
    FOREIGN KEY (`product_id`)
    REFERENCES `next-games-grupo8`.`products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `next-games-grupo8`.`payments`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `next-games-grupo8`.`payments` ;

CREATE TABLE IF NOT EXISTS `next-games-grupo8`.`payments` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `metodo_pago` VARCHAR(45) NOT NULL,
  `order_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_payments_orders_idx` (`order_id` ASC) VISIBLE,
  CONSTRAINT `fk_payments_orders`
    FOREIGN KEY (`order_id`)
    REFERENCES `next-games-grupo8`.`orders` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `next-games-grupo8`.`images`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `next-games-grupo8`.`images` ;

CREATE TABLE IF NOT EXISTS `next-games-grupo8`.`images` (
  `id` INT NOT NULL,
  `images` VARCHAR(255) NOT NULL,
  `products_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_images_products_idx` (`products_id` ASC) VISIBLE,
  CONSTRAINT `fk_images_products`
    FOREIGN KEY (`products_id`)
    REFERENCES `next-games-grupo8`.`products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `next-games-grupo8`.`sub-category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `next-games-grupo8`.`sub-category` ;

CREATE TABLE IF NOT EXISTS `next-games-grupo8`.`sub-category` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL,
  `products_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `product_id_idx` (`products_id` ASC) VISIBLE,
  CONSTRAINT `product_id`
    FOREIGN KEY (`products_id`)
    REFERENCES `next-games-grupo8`.`products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `next-games-grupo8`.`newslatter`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `next-games-grupo8`.`newslatter` ;

CREATE TABLE IF NOT EXISTS `next-games-grupo8`.`newslatter` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `next-games-grupo8`.`banners`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `next-games-grupo8`.`banners` ;

CREATE TABLE IF NOT EXISTS `next-games-grupo8`.`banners` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `image` VARCHAR(255) NOT NULL,
  `products_id` INT NOT NULL,
  `subCategory_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `products_id_idx` (`products_id` ASC) VISIBLE,
  INDEX `subCategory_id_idx` (`subCategory_id` ASC) VISIBLE,
  CONSTRAINT `products_id`
    FOREIGN KEY (`products_id`)
    REFERENCES `next-games-grupo8`.`products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `subCategory_id`
    FOREIGN KEY (`subCategory_id`)
    REFERENCES `next-games-grupo8`.`sub-category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
