-- MySQL Script generated by MySQL Workbench
-- Sat Apr 15 00:08:41 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema next-games-grupo8
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema next-games-grupo8
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `next-games-grupo8` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `next-games-grupo8` ;

-- -----------------------------------------------------
-- Table `next-games-grupo8`.`addresses`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `next-games-grupo8`.`addresses` ;

CREATE TABLE IF NOT EXISTS `next-games-grupo8`.`addresses` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `address` VARCHAR(255) NULL DEFAULT NULL,
  `city` VARCHAR(255) NULL DEFAULT NULL,
  `province` VARCHAR(255) NULL DEFAULT NULL,
  `zipCode` INT NULL DEFAULT NULL,
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `next-games-grupo8`.`estados`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `next-games-grupo8`.`estados` ;

CREATE TABLE IF NOT EXISTS `next-games-grupo8`.`estados` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `images` VARCHAR(255) NULL DEFAULT NULL,
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `next-games-grupo8`.`categories`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `next-games-grupo8`.`categories` ;

CREATE TABLE IF NOT EXISTS `next-games-grupo8`.`categories` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  `estadoId` INT NULL DEFAULT NULL,
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `estadoId` (`estadoId` ASC) VISIBLE,
  CONSTRAINT `categories_ibfk_1`
    FOREIGN KEY (`estadoId`)
    REFERENCES `next-games-grupo8`.`estados` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `next-games-grupo8`.`products`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `next-games-grupo8`.`products` ;

CREATE TABLE IF NOT EXISTS `next-games-grupo8`.`products` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  `price` INT NULL DEFAULT NULL,
  `discount` INT NULL DEFAULT NULL,
  `description` TEXT NULL DEFAULT NULL,
  `visible` TINYINT(1) NULL DEFAULT NULL,
  `CategoryId` INT NULL DEFAULT NULL,
  `image` VARCHAR(255) NULL DEFAULT NULL,
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `CategoryId` (`CategoryId` ASC) VISIBLE,
  CONSTRAINT `products_ibfk_1`
    FOREIGN KEY (`CategoryId`)
    REFERENCES `next-games-grupo8`.`categories` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 51
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `next-games-grupo8`.`subcategories`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `next-games-grupo8`.`subcategories` ;

CREATE TABLE IF NOT EXISTS `next-games-grupo8`.`subcategories` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  `productId` INT NULL DEFAULT NULL,
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `productId` (`productId` ASC) VISIBLE,
  CONSTRAINT `subcategories_ibfk_1`
    FOREIGN KEY (`productId`)
    REFERENCES `next-games-grupo8`.`products` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `next-games-grupo8`.`banners`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `next-games-grupo8`.`banners` ;

CREATE TABLE IF NOT EXISTS `next-games-grupo8`.`banners` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `image` VARCHAR(255) NULL DEFAULT NULL,
  `productsId` INT NULL DEFAULT NULL,
  `subCategoryId` INT NULL DEFAULT NULL,
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `productsId` (`productsId` ASC) VISIBLE,
  INDEX `subCategoryId` (`subCategoryId` ASC) VISIBLE,
  CONSTRAINT `banners_ibfk_1`
    FOREIGN KEY (`productsId`)
    REFERENCES `next-games-grupo8`.`products` (`id`),
  CONSTRAINT `banners_ibfk_2`
    FOREIGN KEY (`subCategoryId`)
    REFERENCES `next-games-grupo8`.`subcategories` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `next-games-grupo8`.`rols`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `next-games-grupo8`.`rols` ;

CREATE TABLE IF NOT EXISTS `next-games-grupo8`.`rols` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `rol` VARCHAR(255) NULL DEFAULT NULL,
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `next-games-grupo8`.`usuarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `next-games-grupo8`.`usuarios` ;

CREATE TABLE IF NOT EXISTS `next-games-grupo8`.`usuarios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `firstName` VARCHAR(255) NULL DEFAULT NULL,
  `LastName` VARCHAR(255) NULL DEFAULT NULL,
  `email` VARCHAR(255) NULL DEFAULT NULL,
  `password` VARCHAR(255) NULL DEFAULT NULL,
  `userName` VARCHAR(255) NULL DEFAULT NULL,
  `image` VARCHAR(255) NULL DEFAULT NULL,
  `rolId` INT NULL DEFAULT NULL,
  `addressId` INT NULL DEFAULT NULL,
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `rolId` (`rolId` ASC) VISIBLE,
  INDEX `addressId` (`addressId` ASC) VISIBLE,
  CONSTRAINT `usuarios_ibfk_1`
    FOREIGN KEY (`rolId`)
    REFERENCES `next-games-grupo8`.`rols` (`id`),
  CONSTRAINT `usuarios_ibfk_2`
    FOREIGN KEY (`addressId`)
    REFERENCES `next-games-grupo8`.`addresses` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `next-games-grupo8`.`orders`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `next-games-grupo8`.`orders` ;

CREATE TABLE IF NOT EXISTS `next-games-grupo8`.`orders` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `date` DATETIME NULL DEFAULT NULL,
  `total` INT NULL DEFAULT NULL,
  `UserId` INT NULL DEFAULT NULL,
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `UserId` (`UserId` ASC) VISIBLE,
  CONSTRAINT `orders_ibfk_1`
    FOREIGN KEY (`UserId`)
    REFERENCES `next-games-grupo8`.`usuarios` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `next-games-grupo8`.`carts`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `next-games-grupo8`.`carts` ;

CREATE TABLE IF NOT EXISTS `next-games-grupo8`.`carts` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `quantity` INT NULL DEFAULT NULL,
  `productId` INT NULL DEFAULT NULL,
  `OrderId` INT NULL DEFAULT NULL,
  `addressId` INT NULL DEFAULT NULL,
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `productId` (`productId` ASC) VISIBLE,
  INDEX `OrderId` (`OrderId` ASC) VISIBLE,
  INDEX `addressId` (`addressId` ASC) VISIBLE,
  CONSTRAINT `carts_ibfk_1`
    FOREIGN KEY (`productId`)
    REFERENCES `next-games-grupo8`.`products` (`id`),
  CONSTRAINT `carts_ibfk_2`
    FOREIGN KEY (`OrderId`)
    REFERENCES `next-games-grupo8`.`orders` (`id`),
  CONSTRAINT `carts_ibfk_3`
    FOREIGN KEY (`addressId`)
    REFERENCES `next-games-grupo8`.`addresses` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `next-games-grupo8`.`images`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `next-games-grupo8`.`images` ;

CREATE TABLE IF NOT EXISTS `next-games-grupo8`.`images` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `image` VARCHAR(255) NULL DEFAULT NULL,
  `productId` INT NULL DEFAULT NULL,
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `productId` (`productId` ASC) VISIBLE,
  CONSTRAINT `images_ibfk_1`
    FOREIGN KEY (`productId`)
    REFERENCES `next-games-grupo8`.`products` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 130
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `next-games-grupo8`.`newslatters`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `next-games-grupo8`.`newslatters` ;

CREATE TABLE IF NOT EXISTS `next-games-grupo8`.`newslatters` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(255) NULL DEFAULT NULL,
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `next-games-grupo8`.`payments`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `next-games-grupo8`.`payments` ;

CREATE TABLE IF NOT EXISTS `next-games-grupo8`.`payments` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `metodoPago` VARCHAR(255) NULL DEFAULT NULL,
  `orderId` INT NULL DEFAULT NULL,
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `orderId` (`orderId` ASC) VISIBLE,
  CONSTRAINT `payments_ibfk_1`
    FOREIGN KEY (`orderId`)
    REFERENCES `next-games-grupo8`.`orders` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `next-games-grupo8`.`sequelizemeta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `next-games-grupo8`.`sequelizemeta` ;

CREATE TABLE IF NOT EXISTS `next-games-grupo8`.`sequelizemeta` (
  `name` VARCHAR(255) COLLATE 'utf8mb3_unicode_ci' NOT NULL,
  PRIMARY KEY (`name`),
  UNIQUE INDEX `name` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
