-- MySQL Script generated by MySQL Workbench
-- Wed Apr 19 22:23:51 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema next-games-grupo8
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema next-games-grupo8
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `next-games-grupo8` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `next-games-grupo8` ;

-- -----------------------------------------------------
-- Table `next-games-grupo8`.`addresses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `next-games-grupo8`.`addresses` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `address` VARCHAR(255) NULL DEFAULT NULL,
  `city` VARCHAR(255) NULL DEFAULT NULL,
  `province` VARCHAR(255) NULL DEFAULT NULL,
  `zipCode` INT NULL DEFAULT NULL,
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `next-games-grupo8`.`states`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `next-games-grupo8`.`states` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  `image` VARCHAR(255) NULL DEFAULT NULL,
  `active` TINYINT(1) NULL DEFAULT NULL,
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `next-games-grupo8`.`products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `next-games-grupo8`.`products` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  `price` INT NULL DEFAULT NULL,
  `discount` INT NULL DEFAULT NULL,
  `description` TEXT NULL DEFAULT NULL,
  `visible` TINYINT(1) NULL DEFAULT NULL,
  `stateId` INT NULL DEFAULT NULL,
  `image` VARCHAR(255) NULL DEFAULT NULL,
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `stateId` (`stateId` ASC) VISIBLE,
  CONSTRAINT `products_ibfk_1`
    FOREIGN KEY (`stateId`)
    REFERENCES `next-games-grupo8`.`states` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 51
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `next-games-grupo8`.`subcategories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `next-games-grupo8`.`subcategories` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `next-games-grupo8`.`banners`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `next-games-grupo8`.`banners` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `image` VARCHAR(255) NULL DEFAULT NULL,
  `productsId` INT NULL DEFAULT NULL,
  `subcategoryId` INT NULL DEFAULT NULL,
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `productsId` (`productsId` ASC) VISIBLE,
  INDEX `subcategoryId` (`subcategoryId` ASC) VISIBLE,
  CONSTRAINT `banners_ibfk_1`
    FOREIGN KEY (`productsId`)
    REFERENCES `next-games-grupo8`.`products` (`id`),
  CONSTRAINT `banners_ibfk_2`
    FOREIGN KEY (`subcategoryId`)
    REFERENCES `next-games-grupo8`.`subcategories` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `next-games-grupo8`.`rols`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `next-games-grupo8`.`rols` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `rol` VARCHAR(255) NULL DEFAULT NULL,
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `next-games-grupo8`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `next-games-grupo8`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `firstName` VARCHAR(255) NULL DEFAULT NULL,
  `LastName` VARCHAR(255) NULL DEFAULT NULL,
  `email` VARCHAR(255) NULL DEFAULT NULL,
  `password` VARCHAR(255) NULL DEFAULT NULL,
  `userName` VARCHAR(255) NULL DEFAULT NULL,
  `image` VARCHAR(255) NULL DEFAULT NULL,
  `rolId` INT NULL DEFAULT NULL,
  `addressId` INT NULL DEFAULT NULL,
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `rolId` (`rolId` ASC) VISIBLE,
  INDEX `addressId` (`addressId` ASC) VISIBLE,
  CONSTRAINT `users_ibfk_1`
    FOREIGN KEY (`rolId`)
    REFERENCES `next-games-grupo8`.`rols` (`id`),
  CONSTRAINT `users_ibfk_2`
    FOREIGN KEY (`addressId`)
    REFERENCES `next-games-grupo8`.`addresses` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `next-games-grupo8`.`orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `next-games-grupo8`.`orders` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `date` DATETIME NULL DEFAULT NULL,
  `total` INT NULL DEFAULT NULL,
  `userId` INT NULL DEFAULT NULL,
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `userId` (`userId` ASC) VISIBLE,
  CONSTRAINT `orders_ibfk_1`
    FOREIGN KEY (`userId`)
    REFERENCES `next-games-grupo8`.`users` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `next-games-grupo8`.`carts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `next-games-grupo8`.`carts` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `quantity` INT NULL DEFAULT NULL,
  `productId` INT NULL DEFAULT NULL,
  `orderId` INT NULL DEFAULT NULL,
  `addressId` INT NULL DEFAULT NULL,
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `productId` (`productId` ASC) VISIBLE,
  INDEX `orderId` (`orderId` ASC) VISIBLE,
  INDEX `addressId` (`addressId` ASC) VISIBLE,
  CONSTRAINT `carts_ibfk_1`
    FOREIGN KEY (`productId`)
    REFERENCES `next-games-grupo8`.`products` (`id`),
  CONSTRAINT `carts_ibfk_2`
    FOREIGN KEY (`orderId`)
    REFERENCES `next-games-grupo8`.`orders` (`id`),
  CONSTRAINT `carts_ibfk_3`
    FOREIGN KEY (`addressId`)
    REFERENCES `next-games-grupo8`.`addresses` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `next-games-grupo8`.`images`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `next-games-grupo8`.`images` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `image` VARCHAR(255) NULL DEFAULT NULL,
  `productId` INT NULL DEFAULT NULL,
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `productId` (`productId` ASC) VISIBLE,
  CONSTRAINT `images_ibfk_1`
    FOREIGN KEY (`productId`)
    REFERENCES `next-games-grupo8`.`products` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 130
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `next-games-grupo8`.`newslatters`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `next-games-grupo8`.`newslatters` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(255) NULL DEFAULT NULL,
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `next-games-grupo8`.`payments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `next-games-grupo8`.`payments` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `methodPayment` VARCHAR(255) NULL DEFAULT NULL,
  `orderId` INT NULL DEFAULT NULL,
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `orderId` (`orderId` ASC) VISIBLE,
  CONSTRAINT `payments_ibfk_1`
    FOREIGN KEY (`orderId`)
    REFERENCES `next-games-grupo8`.`orders` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `next-games-grupo8`.`sequelizemeta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `next-games-grupo8`.`sequelizemeta` (
  `name` VARCHAR(255) COLLATE 'utf8mb3_unicode_ci' NOT NULL,
  PRIMARY KEY (`name`),
  UNIQUE INDEX `name` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `next-games-grupo8`.`subcategoriesproducts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `next-games-grupo8`.`subcategoriesproducts` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `productId` INT NULL DEFAULT NULL,
  `subcategoryId` INT NULL DEFAULT NULL,
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `productId` (`productId` ASC) VISIBLE,
  INDEX `subcategoryId` (`subcategoryId` ASC) VISIBLE,
  CONSTRAINT `subcategoriesproducts_ibfk_1`
    FOREIGN KEY (`productId`)
    REFERENCES `next-games-grupo8`.`products` (`id`),
  CONSTRAINT `subcategoriesproducts_ibfk_2`
    FOREIGN KEY (`subcategoryId`)
    REFERENCES `next-games-grupo8`.`subcategories` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 51
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
